name: Trivy to Jira Security Scan

on:
  workflow_dispatch:
    inputs:
      image:
        description: "Docker image name"
        required: true
      # repo:
      #   description: "GitHub repo to check for Dependabot PRs (owner/repo)"
      #   required: false

jobs:
  security-scan:
    runs-on: ubuntu-latest

    env:
      JIRA_PROJECT_KEY: ${{ secrets.JIRA_PROJECT_KEY }}
      JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
      JIRA_API_TOKEN: ${{ secrets.JIRA_API_TOKEN }}
      JIRA_URL: ${{ secrets.JIRA_URL }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y jq curl wget
          curl -sfL https://raw.githubusercontent.com/aquasecurity/trivy/main/contrib/install.sh | sudo sh

      - name: Run security scan and create Jira ticket
        run: |
          ./jira_single_ticket.sh --image "${{ github.event.inputs.image }}" --repo "${{ github.repository }}"
